#+title: Editable Medications V2 - TODO

[[https://www.figma.com/design/8fpr75UqvO70UFUuM7zvS7/Pending-Orders?node-id=1-2&node-type=canvas&t=14jfXwqdT3PBqYZr-0][Alka's Figma UI Mockup]]

* Investigations, Estimations, and Spikes
** [ ] Make estimations for Editable Meds V2 UI
*** [ ] Estimation for the UI using Jinja templates
**** [ ] Backend
***** [ ] API endpoint for the proposed carts (displayed as "pending orders")
- Note taken on [2024-12-10 Tue 11:03] \\
  We can probably use the ProposedCart API V3 endpoint that already exists. This endpoint currenly only has a POST action, for creating the ProposedCart.
***** [ ] Rewrite the current accept/deny actions to refresh the page instead of redirect to the patient dashboard home page
**** [ ] Frontend
***** [ ] Create table to display the proposed cart
***** [ ] Create "loading" indicator and overlay for when the proposed cart is processing.
- Note taken on [2024-12-10 Tue 11:07] \\
  Apparently Bootstrap 4 does not have a built-in component for this.
***** [ ] Optional: Refactor existing Orders table, use the same Flask component for both ProposedCart and Orders
- Note taken on [2024-12-10 Tue 11:12] \\
  May not be possile. The UI mockup has different fields than the existing table.
*** NO Estimation for the UI using React
Don't think this is a good idea. Won't explore this unless someone says we need to do it.

* [[https://hellowisp.atlassian.net/browse/WISPENG-970][WISPENG-970]]: Editable Meds V2
** [[https://hellowisp.atlassian.net/browse/WISPENG-971][WISPENG-971]]: PreApprovals - Approval Process Automation
*** [X] [[https://hellowisp.atlassian.net/browse/WISPENG-978][WISPENG-978]]: Create new database table for recording proposed cart authorizations
*** [X] [[https://hellowisp.atlassian.net/browse/WISPENG-979][WISPENG-979]]: Populate new database table upon proposed cart creation
:LOGBOOK:
CLOCK: [2024-12-13 Fri 11:35]--[2024-12-13 Fri 11:58] =>  0:23
:END:
*** [X] [[https://hellowisp.atlassian.net/browse/WISPENG-981][WISPENG-981]]: Send new line item data to the server

** [X] [[https://hellowisp.atlassian.net/browse/WISPENG-996][WISPENG-996]]: Pending - Admin Cancel
*** Ask Charlotte if there are other ways to cancel an Order besides going to the \/fill_request\/ page for a patient and hitting void/cancel for a Fill Request
*** Ask Charlotte if we want to consider a way to cancel pending carts in the UI vs. automated.
*** [X] Test that the feature flag works
*** [X] Test that the feature flag works for individual users
*** [X] Test that the cancellation feature only cancels via the UI
*** [X] Test that the cancellation feature does *not* activate during the approval of a proposed cart.
** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/5307][WISPENG-1025]]: Formats provider custom messages for editable meds
** [X] [[https://hellowisp.atlassian.net/browse/WISPENG-1066][WISPENG-1066]]: Update Provider Message On Editable Meds
** [?] WISPENG-973: Void carts
*** [X] Create an admin task when carts are expired
*** [X] Create an Order Activity Log entry when carts are expired
** [-] [[https://hellowisp.atlassian.net/browse/WISPENG-972][WISPENG-972]]: Pending Cart - Daily Email Notification


* Other
Create a ticket for sanitizing provider inputs, see [[https://github.com/hellowisp/secure.hellowisp.com/pull/5307#discussion_r1915795938][this discussion]].

*** [ ] Unticked PR to create a ~GetPackages~ service method
:LOGBOOK:
CLOCK: [2024-12-13 Fri 12:05]--[2024-12-13 Fri 12:33] =>  0:28
:END:
Need this because WISPENG-979 needs to query multiple packages. This is better than querying in a for loop.
