#+title: Projects
#+description: A list of my personal projects

* Games
** Monogame Roguelike
*** Pathfinding
**** [X] Crappy depth first search version
- Note taken on [2024-11-19 Tue 23:23] \\
  Almost there. The enemy correctly moves up, but not left and right. It moves back-and-forth between the same x tiles. It does attack the player if the player is adjacent, so that's progress I guess.
:LOGBOOK:
CLOCK: [2024-11-27 Wed 13:52]
CLOCK: [2024-11-19 Tue 22:00]--[2024-11-19 Tue 23:22] =>  1:22
:END:
**** [X] Better version with Dijkstra's Algorithm
* Web projects
** Goals tracker
Stack: Golang, HTMX, PostgreSQL
** Fire Emblem API
Stack: F#, Giraffe, PostgreSQL.
- What to do for the frontend? React?
* Miscellaneous
** Git diff builder
*** Idea
By inspecting branches (or maybe tags?) in a git repository, construct a set of "diff" files that can be used to display differences between the branches/tags.

The output would look like the code listings in the [[https://rogueliketutorials.com/][Roguelike Tutorial]].

This would make writing new tutorials in that style much, much easier.
*** Technology
It would be cool to write this project on the [[id:e3f7ab88-17ea-4b07-94d5-4498b0681491][.NET]] platform, either with [[id:684e6719-609f-4a8a-a8fa-f11d0585ec10][C#]] or [[id:1c0131b0-54d9-4b00-9214-3920c53984d2][F#]]. It'd probably be easier to start with [[id:684e6719-609f-4a8a-a8fa-f11d0585ec10][C#]] and rewrite to [[id:1c0131b0-54d9-4b00-9214-3920c53984d2][F#]] later.

The [[https://github.com/libgit2/libgit2sharp/wiki][libgit2sharp]] could help a lot here.
** Hacker News reader
*** Idea
A TUI application to read Hacker News.
*** Technology
**** API
The [[https://github.com/HackerNews/API][Hacker News API]] could be used to get the stories to dislay. Maybe the comments and upvotes as well.
**** TUI
I'm thinking the Go programming language with something like [[https://github.com/charmbracelet/bubbletea][Bubble Tea]] for the TUI portion.
