* Inbox
** [X] Write a Jira ticket that describes the issue with the DoseSpot Pharmacy Search form. It does not mark the required fields as needed
SCHEDULED: <2024-04-02 Tue>
** [ ] Investigate Emacs Meow mode for Doom Emacs
** [ ] Investigate separating my journal into its own git submodule
- Note taken on [2024-03-20 Wed 22:34] \\
  There are things I may write in my org-journal that I *really* don't want on my work laptop. Putting it in its own Git submodule that is separated would solve this problem.
** [ ] Investigate having a separate TODO list for work related tasks.
- Note taken on [2024-03-20 Wed 22:36] \\
  Not a high priority right now, as removing work stuff later probably isn't too hard.
- Note taken on [2024-03-20 Wed 22:35] \\
  I don't necessarily want to pollute my personal TODOs with work stuff.

** [X] Investigate the Key Promoter plugin for JetBrains IDEs

** [1/1] Work on Wezterm config
*** [X] When opening Wezterm at work, automatically open tabs to all project directories
:LOGBOOK:
CLOCK: [2024-10-16 Wed 09:00]--[2024-10-16 Wed 10:17] =>  1:17
:END:
** [X] Call EECU about the strange wire transfer to my account
DEADLINE: <2024-10-16 Wed>
** [X] Call EECU about a new wire transfer form

** [ ] Write a message to Seiji on LinkedIn
DEADLINE: <2024-12-24 Tue>
