:PROPERTIES:
:ID:       7b30e3f2-99be-409d-96b8-9e313f906b05
:END:
#+title: Adaptability

* Lack of Adaptability today
Many people are not very adaptable today. This is because of all the choice we have in modern society.

- Don't like that video game? There's hundreds more out there!
- Don't like your job? Just get another!
- Don't like one small aspect of that person on Tinder? Just keep swiping!

* Black and White thinking
"Black and white" thinking is a cause of mental illness in may people. This thinking focuses on extremes, and leaves no gray area in a person's thoughts.
Examples:
- I will die alone.
- I will always be miserable.
- I will never be as good at this other person at this thing.

Thinking like this will lead to a self-fulfilling prophecy of misery and despair. If you believe you will always be miserable, you won't try things to get better. If you believe you will never be good enough, you won't try to improve.

But nobody can predict the future! Instead, try to see things less "black and white".

If you find yourself thinking these black-and-white thoughts, try catch those thoughts and try to reframe them:
- I am lonely now, but perhaps I will find someone. I just need to improve myself.
- I am sad now, but I do have things going for me in my life.
- Maybe I'm not as good as this other person in this aspect, but I will try my best to improve and be a better version of myself.

Think about the good things in your life, and try to reframe your thoughts. Don't give in to doomerism.


* Consider what others have to say
Consider other's perspectives when hearing something you disagree with. Most of us dismiss something someone says out of hand when hearing something that contradicts what we believe. Try to listen to what they have to say, and consider it.

"Steel man" their position. See if what they say could make sense to you.

People will often ask for advice in an area they struggle in, only to negatively respond when others try to give advice. Try to think about the advice you receive, and at least try what others suggest before dismissing them out of hand.

* Cogintive flexibility
Any time you think "This doesn't work for me", try reframing it in your mind to "This is a challenge for me to overcome".

Those who see these challenges as obstacles to overcome will be more adaptable, and therefore more successful in life.

Studies show that Cognitive Flexibility strongly correlates to improving in ranking in games!
