:PROPERTIES:
:ID:       2b730c77-767a-4547-b1bf-53428b3d33a5
:END:
#+title: ASP.NET Core

A web backend for [[id:684e6719-609f-4a8a-a8fa-f11d0585ec10][C#]].

Utilizes the [[id:800d6eac-df47-4e23-88d8-bf19cea3ca11][Kestrel]] web server by default.

* CLI
Run the CLI with `dotnet` command.

To get the dependencies:

#+BEGIN_SRC bash
dotnet restore
#+END_SRC

To compile an application from the CLI:

#+BEGIN_SRC bash
dotnet build
#+END_SRC

`dotnet build` runs `dotnet restore` implicitly. `--no-restore` can be used to skip that step.

To run the application:

#+BEGIN_SRC bash
dotnet run
#+END_SRC

`dotnet run` runs `dotnet restore` implicitly. `--no-restore` can be used to skip that step.
`dotnet run` runs `dotnet build` implicitly. `--no-build` can be used to skip that step.

* Minimal API
To create a minimal API application with the CLI, run the commands:

#+BEGIN_SRC bash
dotnet new sln -n WebApplication1
dotnet new web -o WebApplication1
dotnet sln add WebApplication1
#+END_SRC

* File structure
** appsettings.json
TODO
** appsettings.Development.json
TODO
** .csproj
Project file. Contains info on how to build the project, along with [[id:1b80e77a-7d4e-4f61-8a72-ab227d2363e7][NuGet]] dependencies.

It defines the type of project (web/console/library), and the platform (.NET Core, .NET 7, etc.).
** Properties
Subfolder. TODO
*** launchSettings.json
Controls how the application is run.
** .sln
"Solution" file, outside the project directory.

* Inversion of Control
[[id:2b730c77-767a-4547-b1bf-53428b3d33a5][ASP.NET Core]] uses Inversion of Conrol to register services.
TODO: More about this!

* Middleware
Middleware can be added to the [[id:496ff34c-5052-41b5-85be-de05b1ae56cc][WebApplication]] instance once it is created.

Middleware consists of small components that execute in sequence when the application receives an [[id:fdec7db4-2c96-40f2-8f66-916ef0839bd0][HTTP]] request.

Middleware is usually added to [[id:496ff34c-5052-41b5-85be-de05b1ae56cc][WebApplication]] by calling `Use*` extension methods. For example, for logging:

#+NAME: Use* Example
#+BEGIN_SRC csharp
if (app.Environment.IsDevelopment())
{
   app.UseHttpLogging();
}
#+END_SRC

The order that middleware is added to the pipeline is important. Middleware can only access previously added middleware.

[[id:496ff34c-5052-41b5-85be-de05b1ae56cc][WebApplication]] automatically adds several pieces of middleware including the two most important ones: [[id:72c55ed6-f8cf-4da7-9465-e768787a908f][RoutingMiddleware]], and [[id:fe0e544d-60a0-4d1b-b6f7-761deeba4d07][EndpointMiddleware]]  . Routing is added to the beginning of the pipeline. Endpoint middleware is added to the end. Other middleware automatically added includes exception handling

In [[id:2b730c77-767a-4547-b1bf-53428b3d33a5][ASP.NET Core]], middleware is a [[id:684e6719-609f-4a8a-a8fa-f11d0585ec10][C#]] class that can handle an [[id:fdec7db4-2c96-40f2-8f66-916ef0839bd0][HTTP]] request or response. It can:
- Take an [[id:fdec7db4-2c96-40f2-8f66-916ef0839bd0][HTTP]] request and turn it into an [[id:fdec7db4-2c96-40f2-8f66-916ef0839bd0][HTTP]] response.
- Modify an [[id:fdec7db4-2c96-40f2-8f66-916ef0839bd0][HTTP]] request and pass it to another piece of middleware.
- Modify an [[id:fdec7db4-2c96-40f2-8f66-916ef0839bd0][HTTP]] response and pass it to either another middleware or to the web server.

  When middleware short-circuits the pipeline and returns a response, it's called a "terminal middleware".

  The pipeline is bidirectional. The request passes through each middleware, being manipulated until it turns into a response. Then, the response passes through each middleware _again_, in reverse order, until it gets back to the first piece of middleware.

  The middleware pipeline could also be thought of as a series of nested components, with the first component being the outermost one, and the last being the innermost component.

  If no middleware returns a response object, a [[id:47016693-9eec-4754-963d-a42bdc4626ce][404]] is returned automatically.

** [[id:f793ab94-21b5-452f-979f-cb7906d3c0b9][DeveloperExceptionPageMiddleware]]
** [[id:fb621db6-9121-48bf-9288-c447820ace80][ExceptionHandlerMiddleware]]
** [[id:f61b0c4f-d2fd-4a66-a6d8-5f6249fbcdba][StaticFileMiddleware]]
** [[id:b91253da-c86d-4882-a061-79f4e822e5b6][StatusCodePagesMiddleware]]
** [[id:3b5d2cc3-c0d5-4a8b-ba4e-4c666660613a][WelcomeMiddleware]]

* Parametrized routes
Parameters can be created in URLs for the minimal API by using the angled brackets in the string, like `/person/{someValue}`

#+NAME: ASP.NET Core - Minimal API parametrized routes example
#+BEGIN_SRC csharp
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);
WebApplication app = builder.Build();

var people = new List<Person>
{
    new("Tom", "Hanks"),
    new("Denzel", "Washington"),
    new("Leondardo", "DiCaprio"),
    new("Al", "Pacino"),
    new("Morgan", "Freeman"),
};

app.MapGet("/person/{name}", (string name) =>
    people.Where(p => p.FirstName.StartsWith(name)));

app.Run();
#+END_SRC

* Results
See [[id:53c35714-f4fa-4b14-ac08-8baab165f689][Results]] and [[id:8cfc8c9d-8fac-4060-8bd8-c915ca3af44e][TypedResults]]

* Endpoint Filters
Call ~.AddEndpointFilter~ on ~MapGet~ to add a common validation filter to an endpoint.
[[https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/min-api-filters?view=aspnetcore-8.0][Microsoft Docs]] (v8)
Like the middleware pipeline, you can build an endpoint filter pipeline that can short-circuit itself and return early.
Filters have additional info that middleware does not, like the endpoint details.
Filters run only on endpoints they are registered to, whereas middleware runs for every request.

You can supply an implementation of [[id:5ee86319-9af0-45e6-ae54-730eac54015a][IEndpointFilter]] to ~.AddEndpointFilter~.

* Middleware vs Filters
Middleware is more general, whereas filters are run on specific endpoints.

* Route Groups
~MapGroup~ can be used to group APIs together under common prefixes.
~MapGroup~ can be chained:
#+BEGIN_SRC csharp
app.MapGroup("/fruit").MapGroup("/citrus")
#+END_SRC
This results in "/fruit/citrus"

* Route Constraints
:PROPERTIES:
:ID:       4200012c-3779-49b8-aab1-da24b57bd065
:END:
Used to decided if a request can be routed to a particular endpoint. *Not* for input validation, as a mismatch will result in a [[id:fdec7db4-2c96-40f2-8f66-916ef0839bd0][HTTP]] [[id:47016693-9eec-4754-963d-a42bdc4626ce][404]] error, not a [[id:b5c700c1-861a-4c56-a177-249d2a2af05f][400]].

[[https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-8.0#route-constraints][Microsoft Docs (v8)]]

| constraint        | Example                                   | Example Matches                      | Notes                                                                                   |
|-------------------+-------------------------------------------+--------------------------------------+-----------------------------------------------------------------------------------------|
| int               | {id:int}                                  | 123456789, -123456789                | Matches any integer                                                                     |
| bool              | {active:bool}                             | true, FALSE                          | Matches true or false. Case-insensitive                                                 |
| datetime          | {dob:datetime}                            | 2016-12-31, 2016-12-31 7:32pm        | Matches a valid DateTime value in the invariant culture. See preceding warning.         |
| decimal           | {price:decimal}                           | 49.99, -1,000.01                     | Matches a valid decimal value in the invariant culture. See preceding warning.          |
| double            | {weight:double}                           | 1.234, -1,001.01e8                   | Matches a valid double value in the invariant culture. See preceding warning.           |
| float             | {weight:float}                            | 1.234, -1,001.01e8                   | Matches a valid float value in the invariant culture. See preceding warning.            |
| guid              | {id:guid}                                 | CD2C1638-1638-72D5-1638-DEADBEEF1638 | Matches a valid Guid value                                                              |
| long              | {ticks:long}                              | 123456789, -123456789                | Matches a valid long value                                                              |
| minlength(value)  | {username:minlength(4)}                   | Rick                                 | String must be at least 4 characters                                                    |
| maxlength(value)  | {filename:maxlength(8)}                   | MyFile                               | String must be no more than 8 characters                                                |
| length(length)    | {filename:length(12)}                     | somefile.txt                         | String must be exactly 12 characters long                                               |
| length(min,max)   | {filename:length(8,16)}                   | somefile.txt                         | String must be at least 8 and no more than 16 characters long                           |
| min(value)        | {age:min(18)}                             | 19                                   | Integer value must be at least 18                                                       |
| max(value)        | {age:max(120)}                            | 91                                   | Integer value must be no more than 120                                                  |
| range(min,max)    | {age:range(18,120)}                       | 91                                   | Integer value must be at least 18 but no more than 120                                  |
| alpha             | {name:alpha}                              | Rick                                 | String must consist of one or more alphabetical characters, a-z and case-insensitive.   |
| regex(expression) | {ssn:regex(^\\d{{3}}-\\d{{2}}-\\d{{4}}$)} | 123-45-6789                          | String must match the regular expression. See tips about defining a regular expression. |
| required          | {name:required}                           | Rick                                 | Used to enforce that a non-parameter value is present during URL generation             |

Constraints can be combined with the colon. Example: ~{qty:int:max(10)?}~ matches ~3, -123, 0, null~ (optional integer of 10 or less).

Best used sparingly. With good URL design, route constraints won't be needed most of the time. They are most useful when URLs overlap.

* [[id:81a41be1-2983-4a8a-b68b-22b41a39c54c][Catch-all Parameters]]

* [[id:08f2d5da-98ab-49b0-93fe-bc39d96f06d9][Minimal API]]

* [[id:fdfd76f1-ea62-40fc-9cbc-ba323ca0b5cc][Dependency Injection]] Container

** Registering services with the DI container
To register services, use ~WebApplication.Add*~ (~[[id:496ff34c-5052-41b5-85be-de05b1ae56cc][WebApplication]].AddScoped, [[id:496ff34c-5052-41b5-85be-de05b1ae56cc][WebApplication]].AddSingleton, or [[id:496ff34c-5052-41b5-85be-de05b1ae56cc][WebApplication]].AddTransient)

#+BEGIN_SRC csharp
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.Services.AddScoped<IEmailSender, EmailSender>();
builder.Services.AddScoped<NetworkClient>();  // The service type and implementation are the same, so no need to specify twice.
builder.Services.AddSingleton<MessageFactory>();

WebApplication app = builder.Build();

app.MapGet("/register/{username}", RegisterUser);

app.Run();

string RegisterUser(string username, IEmailSender emailSender)
{
    emailSender.SendEmail(username);
    return $"Email sent to {username}!";
}
#+END_SRC

** Registering a service with a lambda

#+BEGIN_SRC csharp
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.Services.AddScoped<IEmailSender, EmailSender>();
builder.Services.AddScoped<NetworkClient>();
builder.Services.AddSingleton<MessageFactory>();
builder.Services.AddScoped(  // Uses a lambda to register the service.
    provider =>
        new EmailServerSettings(
            Host: "smpt.server.com",
            Port: 25
        ));

WebApplication app = builder.Build();

app.MapGet("/register/{username}", RegisterUser);

app.Run();

string RegisterUser(string username, IEmailSender emailSender)
{
    emailSender.SendEmail(username);
    return $"Email sent to {username}!";
}
#+END_SRC

** Creating an extension method to tidy up adding multiple services
Using an extension method can make things easier to read.

#+BEGIN_SRC csharp
public static class EmailSenderServiceCollectionExtensions
{
    public static IServiceCollection AddEmailSender(
        this IServiceCollection services)
    {
        services.AddScoped<IEmailSender, EmailSender>();
        services.AddSingleton<NetworkClient>();
        services.AddScoped<MessageFactory>();
        services.AddSingleton(
            new EmailServerSettings
            (
                host: "smtp.server.com",
                port: 25
            ));
        return services;
    }
}
#+END_SRC

#+BEGIN_SRC csharp
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.Services.AddEmailSender();

WebApplication app = builder.Build();

app.MapGet("/register/{username}", RegisterUser);

app.Run();
#+END_SRC

** Registering multiple services
Suppose we want to send a message to a user via email, SMS, and Facebook all at once when a new user registers on our site. We can write multiple implementations of ~IMessageSender~ for each of these, and register them all to the DI container.

#+BEGIN_SRC csharp
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);
builder.Services.AddScoped<IMessageSender, EmailSender>();
builder.Services.AddScoped<IMessageSender, SmsSender>();
builder.Services.AddScoped<IMessageSender, FacebookSender>();
#+END_SRC

Then, inject ~IEnumerable<IMessageSender>~ into ~RegisterUser~ and iterate through each one.

#+BEGIN_SRC csharp
string RegisterUser(
    string username,
    IEnumerable<IMessageSender> senders)
{
    foreach(var sender in senders)
    {
        Sender.SendMessage($"Hello {username}");
    }

    return $"Welcome message sent to {username}";
}
#+END_SRC

*** Injecting a single service when multiple are registered
What if we have registered multiple services, but we need only one?

#+BEGIN_SRC csharp
public class SingleMessageSender
{
   private readonly IMessageSender _messageSender;
   public SingleMessageSender(IMessageSender messageSender)
   {
       _messageSender = messageSender;
   }
}
#+END_SRC

In this example, we only need one ~IMessageSender~. Because it was the last one registered, ~FacebookSender~ will be used by default.

** Lifetimes
There are three lifetimes to consider when registering a service.

- Transient: A new service is requested for every request.
- Scoped: Within a scope, all requests for a service give you the same object. Each web request gets its own scope.
- [[id:751f6a14-386c-46b9-806a-f51d20fd1e31][Singleton]]: Always get the same instance of the service.

*** Transient
Like calling ~new~ every time you need an object. Creates a lot of objects.

Not used often.

*** Scoped
The most commom lifetime, due to the nature of Web requests.

Useful for anything that uses a database, is dependent on the HTTP request, or anything that uses another scoped service.

*** [[id:751f6a14-386c-46b9-806a-f51d20fd1e31][Singleton]]
Created when it's first needed, and reused every other time.

Convenient for objects that need to be shared, or that are immutable and expensive to create. For example, a caching service.

Any service registered as a singleton should be thread-safe.

*** Captive dependencies
If service ~A~ is scoped, and service ~B~ is a singleton, and if service ~A~ is injected into ~B~, then ~A~ will keep getting reused, even though it should be scoped.

Captive dependencies can cause subtle, hard to track bugs, so think carefully when registering a singleton service.

ASP.NET Core should automatically check for captive dependencies, but it comes at a performance cost, so it's only enabled in dev environments.

* Configuration
Configuration is handled through the [[id:11f264bb-5b70-441b-a047-85b960e0c66b][ConfigurationManager]].

#+BEGIN_SRC csharp
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.Configuration.Sources.Clear();
builder.Configuration.AddJsonFile("appsettings.json", optional: true);

WebApplication app = builder.Build();

app.MapGet("/", () => app.Configuration.AsEnumerable());

app.Run();
#+END_SRC

Accessing a configuration object in places other than ~Program.cs~ can be done by injecting [[id:11f264bb-5b70-441b-a047-85b960e0c66b][ConfigurationManager]] (it is registered in the [[id:fdfd76f1-ea62-40fc-9cbc-ba323ca0b5cc][Dependency Injection]] container as [[id:21bb745d-76ad-4672-9fdb-9b9c09285c5a][IConfiguration]]).

** Multiple configuration providers.

It is possible to have configuration from multiple places, simply by adding them to [[id:11f264bb-5b70-441b-a047-85b960e0c66b][ConfigurationManager]].

Be aware that order matters. If values share the same key, later values will override earlier ones.

#+BEGIN_SRC csharp
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.Configuration.Sources.Clear();
builder.Configuration
    .AddJsonFile("sharedSettings.json", optional: true);
builder.Configuration.AddJsonFile("appsettings.json", optional: true);
builder.Configuration.AddEnvironmentVariables();

WebApplication app = builder.Build();

app.MapGet("/", () => app.Configuration.AsEnumerable());

app.Run();
#+END_SRC

** Reloading on change

It's possible to modify configuration on the fly by providing the ~reloadOnChange~ argument.

#+BEGIN_SRC csharp
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.Configuration.Sources.Clear();
builder.Configuration
    .AddJsonFile(
        "appsettings.json",
        optional: true,
        reloadOnChange: true);

WebApplication app = builder.Build();

app.MapGet("/", () => app.Configuration.AsEnumerable());

app.Run();
#+END_SRC

This sets up a file watcher in the background, so be aware that it's not "free" performance wise.

** Strongly typed options

Instead of a bunch of magic string keys everywhere, and every config value being interpreted as a string, it's possible to load configuration into strongly typed [[id:684e6719-609f-4a8a-a8fa-f11d0585ec10][C#]] objects.

Take the following example of an options class:

#+BEGIN_SRC csharp
public class AppDisplaySettings
{
   public string Title { get; set; }
   public bool ShowCopyright { get; set; }
}
#+END_SRC

(Note: options classes need to be non-abstract and have a ~public~ parameterless constructor)

You can also have more complex types than ~string~ and ~bool~.

#+BEGIN_SRC csharp
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.Services.Configure<MapSettings>(
    builder.Configuration.GetSection("MapSettings"));  // The section name can be any value, it doesn't have to match the name of the class.
builder.Services.Configure<AppDisplaySettings>(
    builder.Configuration.GetSection("AppDisplaySettings"));
#+END_SRC

The above is an example of using [[id:4c83ade3-50b9-4b66-93ca-1961cb9219cb][IOptions<T>]].

** Configuring for multiple environments

The environment variable ~ASPNETCORE_ENVIRONMENT~ is used to set the type of environment. The three commonly used ones are:
- "Development"
- "Staging"
- "Production"

There are several helper methods available when sticking with these values:
- IHostEnvironment.IsDevelopment()
- IHostEnvironment.IsStaging()
- IHostEnvironment.IsProduction()
- IHostEnvironment.IsEnvironment(string environmentName)


It's possible to load configuration based on the environment

#+BEGIN_SRC csharp
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

IHostEnvironment env = builder.Environment;

builder.Configuration.Sources.Clear();
builder.Configuration
    .AddJsonFile(
        "appsettings.json",
        optional: false)
    .AddJsonFile(
        $”appsettings.{env.EnvironmentName}.json”,
        Optional: true);

WebApplication app = builder.Build();

app.MapGet("/", () =>"Hello world!");

app.Run();
#+END_SRC

Example of using the [[id:fb621db6-9121-48bf-9288-c447820ace80][ExceptionHandlerMiddleware]] in non-dev environments:

#+BEGIN_SRC csharp
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.AddProblemDetails();

WebApplication app = builder.Build();

if (!builder.Environment.IsDevelopment())
{
    app.UseExceptionHandler();
}

app.MapGet("/", () =>"Hello world!");

app.Run();
#+END_SRC

Also note that it's possible to set your environment via the CLI tool like this:

#+BEGIN_SRC shell
dotnet run --no-launch-profile --environment Staging
#+END_SRC
