:PROPERTIES:
:ID:       ccd90ef7-390c-4623-9a21-49340850109b
:END:
#+title: Javascript

Javascript is a language that proves that Stockholm Syndrome exists.

* Destructuring
:PROPERTIES:
:ID:       5f7b067c-aba1-40f8-adda-6ce2ef1b7dea
:ROAM_REFS: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment
:END:

Destructuring in [[id:ccd90ef7-390c-4623-9a21-49340850109b][Javascript]] is a way to unpack values from arrays, properties, or objects into distinct variables.

#+BEGIN_SRC javascript
let a, b, rest;
[a, b] = [10, 20];

console.log(a);
// Expected output: 10

console.log(b);
// Expected output: 20

[a, b, ...rest] = [10, 20, 30, 40, 50];

console.log(rest);
// Expected output: Array [30, 40, 50]
#+END_SRC

* Rest Operator
:PROPERTIES:
:ID:       c66f10cf-8136-430a-8b7c-17b259490cc2
:END:

The rest operator allows for [[id:5a16a4b5-16ec-412b-8aa7-d021785b70d7][variadic functions]] in [[id:ccd90ef7-390c-4623-9a21-49340850109b][Javascript]].

#+BEGIN_SRC javascript
function sum(...theArgs) {
  let total = 0;
  for (const arg of theArgs) {
    total += arg;
  }
  return total;
}

console.log(sum(1, 2, 3));
// Expected output: 6

console.log(sum(1, 2, 3, 4));
// Expected output: 10
#+END_SRC

A function may only have one rest parameter.

This can also be used to assign variables from an object.

#+BEGIN_SRC javascript
const someObject = { a: 1, b: 2, c: 3, d: 4 };
const { a, b, ...otherAttrs } = someObject;
#+END_SRC

~otherAttrs~ will get ~c~ and ~d~ in this case.

* Undefined
:PROPERTIES:
:ID:       ef839e85-abd9-45fd-867c-4933be461e39
:END:

TODO

* Events
:PROPERTIES:
:ID:       77b9d50f-bd7f-4021-9794-509347634cc0
:ROAM_REFS: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events
:END:

[[id:ccd90ef7-390c-4623-9a21-49340850109b][Javascript]] events are "things" that happen in the system (in this case, happen to [[id:b785b344-47c9-4993-96a6-6a267af835b1][HTML]] elements).

Events have three phases.
- Capture phase: Events are dispatched to all parent [[id:d99e159b-96af-4464-831b-b812e5621144][DOM]] nodes in descending order, starting with the window element, going through every ancestor, and ending at the parent of the target element.
- Target phase: An event is dispatched to the target element itself.
- Bubble phase: Events are dispatched to all parent [[id:d99e159b-96af-4464-831b-b812e5621144][DOM]] nodes in ascending order, starting with the parent of the target element and moving up through the ancestors until the window element.

To add an event listener to a [[id:d99e159b-96af-4464-831b-b812e5621144][DOM]] element (bubble and target), use [[id:8fb566bf-8bbf-4610-853b-0a1747661075][addEventListener]].

#+BEGIN_SRC javascript
element.addEventListener("click", onClick);
#+END_SRC

To use a capture listener instead:

#+BEGIN_SRC javascript
element.addEventListener("click", onClick, { capture: true });
#+END_SRC

You can use the ~.eventPhase~ property on the event object to see which phase an event belongs to.

- Event.CAPTURING_PHASE (1) for capture
- Event.AT_TARGET (2) for target
- Event.BUBBLING_PHASE (3) for bubble
