:PROPERTIES:
:ID:       0cc53aca-8ee6-40a2-8c7e-9223cd8e2911
:END:
#+title: Restaurants

A list of restaurants and our feelings about them.

* Clovis
** Gulab Indian Bistro
*** Chicken Curry
Okay. Probably won't get again

*** Garlic Naan
Pooja does not like this, says it's too oily.

*** Gulab Jamun
Pretty good

*** Mango Lassi
Good

*** Samosas
Good. The sweet sauce that comes with it is very good.

** Phoenician Mediterranean Grill
Don't order again. It made Pooja and Marcus sick after eating the salmon.

** Ramen Hayashi
Pooja did not like this one when she was pregnant with Marcus, but she likes it again now.

*** Chicken Egg Rolls
Pooja likes these.

** Tandoori Pizza
Good overall

*** Potato Pizza
Good!

*** Achari Wings
"Authentic", but not as good as Curry Pizza wings

*** Tandoori Wings
Not bad, but also not as good as Curry Pizza's wings

*** Mango Lassi
Aurora likes it. I think it's alright. Pooja did not like it that much.

* Monterey
** El Cantaro
791 Foam St, Monterey, CA 93940

*** Chicken Quesadilla
Tortilla reminded Pooja of authentic Indian food. Very good.

*** Potato Crispy Tacos
Very good

** First Awakenings
300 David Ave, Monterey, CA 93940

Pretty good. Wave Street Cafe is better.

** Gianni's Pizza
725 Lighthouse Ave, Monterey, CA 93940

Great both times we went.

** Namaste Indian Bistro
538 Lighthouse Ave, Monterey, CA 93940

Pretty good. They gave us no silverware for a takeout order, which made eating it in the hotel a bit difficult.

** Rock N Roll Donut Bar
685 Cannery Row Suite 101, Monterey, CA 93940

Alright. Not as good as we had hoped. We got a generic chocolate donut and a blue (vanilla) frosting one with sprinkles. Both alright but nothing that special.

** Wave Street Cafe
550 Wave St, Monterey, CA 93940

Gone twice, was great both times
