:PROPERTIES:
:ID:       0cc53aca-8ee6-40a2-8c7e-9223cd8e2911
:END:
#+title: Restaurants

A list of restaurants and our feelings about them.

* Clovis
** Curry Pizza Company
*** Pizza
**** The Savage Pizza
Their version of a combo. This is what Aurora likes.

*** Wings
**** Curry Madala Rub
Not Spicy.

Aurora likes these a lot, and so does Pooja.
** Gulab Indian Bistro
*** Chicken Curry
Okay. Probably won't get again

*** Garlic Naan
Pooja does not like this, says it's too oily.

*** Gulab Jamun
Pretty good

*** Mango Lassi
Good

*** Samosas
Good. The sweet sauce that comes with it is very good.

** Phoenician Mediterranean Grill
Don't order again. It made Pooja and Marcus sick after eating the salmon.

** Ramen Hayashi
Pooja did not like this one when she was pregnant with Marcus, but she likes it again now.

*** Chicken Egg Rolls
Pooja likes these.

** Tandoori Pizza
Good overall

*** Potato Pizza
Good!

*** Achari Wings
"Authentic", but not as good as Curry Pizza wings

*** Tandoori Wings
Not bad, but also not as good as Curry Pizza's wings

*** Mango Lassi
Aurora likes it. I think it's alright. Pooja did not like it that much.

* Monterey
** El Cantaro
791 Foam St, Monterey, CA 93940

*** Chicken Quesadilla
Tortilla reminded Pooja of authentic Indian food. Very good.

*** Potato Crispy Tacos
Very good

** First Awakenings
300 David Ave, Monterey, CA 93940

Pretty good. Wave Street Cafe is better.

** Gianni's Pizza
725 Lighthouse Ave, Monterey, CA 93940

Great both times we went.

** Namaste Indian Bistro
538 Lighthouse Ave, Monterey, CA 93940

Pretty good. They gave us no silverware for a takeout order, which made eating it in the hotel a bit difficult.

** Rock N Roll Donut Bar
685 Cannery Row Suite 101, Monterey, CA 93940

Alright. Not as good as we had hoped. We got a generic chocolate donut and a blue (vanilla) frosting one with sprinkles. Both alright but nothing that special.

** Wave Street Cafe
550 Wave St, Monterey, CA 93940

Gone twice, was great both times

* Dublin
** Denica's Real Food Kitchen
Very good! Would make this a regular breakfast spot if we lived here.

*** Souffle Pancakes
Really good. Takes awhile to make though.

*** Fruit Pancakes?
Very good.

*** Black Coffee
Good, don't know what brand it was but we liked it. Nothing incredible but still good.

*** Ube latte
Very good. A bit too sweet for my taste for morning coffee. Makes me want to try the other Ube deserts that they have!

** Falafel town, house of Mediterranean
*** Spicy Gyro
I liked it, big portion

** Mandarin Delight
Really good. Would make this our regular Chinese place if we lived there.

Lots of food. Could just order _one_ thing and that would be enough for all of us.

Very friendly staff.

** Croffles - Waffle place in the mall
Great! We enjoyed both things we got. The strawberry one and one other, can't remember.


* Walnut Creek
** Melo's Italian Table
Good!

*** Appetizer Bread?
Pretty good.
*** Some other pasta? Don't remember
It was good. Don't remember exactly what it was though.
*** Spaghetti with red sauce?
This was just alright. Not bad, but nothing special.
