#+title: Daily
#+description: This is a test file to try time-blocking in Org Mode

* <2025-03-31 Mon>
** [X] Call: Eng Team Quick Update! - Exciting things!
SCHEDULED: <2025-03-31 Mon 11:30-11:45>
** [X] Look into separating DoseSpot from the Rx model
SCHEDULED: <2025-03-31 Mon 13:00-15:00>
** [X] Study
SCHEDULED: <2025-03-31 Mon 15:00-16:00>
** [ ] Test the Flask 2.1 branch (possibly with Kian and Amanda)

* <2025-04-01 Tue>
** [X] Figure out the flask-login thing
** [X] Discuss the business logic "workflows" concept
SCHEDULED: <2025-04-01 Tue 11:30-12:00>
** [X] Study
SCHEDULED: <2025-04-01 Tue 15:20-16:20>
** [X] Start work on the columns to get us decoupled from DoseSpot (also write the Jira tickets)
SCHEDULED: <2025-04-01 Tue 16:30-18:30>

* <2025-04-02 Wed>
** [X] Canvas Eng Sync
SCHEDULED: <2025-04-02 Wed 09:30-10:20>
** [X] Try to get one failing test in ~flask-login~ branch working
SCHEDULED: <2025-04-02 Wed 10:30-11:20>
- Note taken on [2025-04-02 Wed 09:38] \\
  Might need to delete the test if it just doesn't work.
** [X] Work on DoseSpot decoupling
SCHEDULED: <2025-04-02 Wed 11:30-17:00>

* <2025-04-03 Thu>
** [X] Canvas Eng Sync
SCHEDULED: <2025-04-03 Thu 09:00-10:30>
** [X] Continue work on DoseSpot decoupling

* <2025-04-07 Mon>
** [X] Heads down Canvas time
SCHEDULED: <2025-04-07 Mon 08:00-13:00>
** [X] Work on removing unused DoseSpot vars
- Note taken on [2025-04-07 Mon 17:47] \\
  Prescriptions table: last entry was in February of 2023.

* <2025-04-08 Tue>
** [X] Heads down Canvas time
SCHEDULED: <2025-04-08 Tue 08:00-13:00>
** [X] Work on DoseSpot decoupling
SCHEDULED: <2025-04-08 Tue 13:30-15:30>
** [X] Read "Cosmic Python": Chapter 2
SCHEDULED: <2025-04-08 Tue 15:45-17:00>

* <2025-04-09 Wed>
** [X] Canvas meeting
SCHEDULED: <2025-04-09 Wed 08:00-09:00>
** [X] Book club
SCHEDULED: <2025-04-09 Wed 11:00-12:00>
** [X] Canvas meeting
SCHEDULED: <2025-04-09 Wed 12:00-13:00>
** [X] DoseSpot decoupling
SCHEDULED: <2025-04-09 Wed 13:30-16:00>
** [X] Study
SCHEDULED: <2025-04-09 Wed 16:00-17:00>

* <2025-04-14 Mon>
** [-] Test token expiration for Flask 2.1 PR
SCHEDULED: <2025-04-14 Mon 10:00-10:30>
** [ ] [[https://hellowisp.atlassian.net/browse/WISPENG-1480][WISPENG-1480]]: Backfill 'erx_refills' data from the 'dosespot_rx' data
SCHEDULED: <2025-04-14 Mon 10:45-12:00>
** [ ] [[https://github.com/hellowisp/secure.hellowisp.com/pull/5732][WISPENG-1476]]: Removes authorizations validator in AddProposedCartRequest
- Note taken on [2025-04-14 Mon 09:03] \\
  Need to manually test this to make sure I didn't break the whole damn feature.
** [ ] Study
SCHEDULED: <2025-04-14 Mon 13:30-14:45>
** [ ] Deploy [[https://github.com/hellowisp/secure.hellowisp.com/pull/5607][Flask 2.1 PR]]
SCHEDULED: <2025-04-14 Mon 15:00-17:00>
- Note taken on [2025-04-14 Mon 09:07] \\
  Might want to take the primary on-call shift as well, just in case.
- Note taken on [2025-04-14 Mon 09:04] \\
  I may need to do this with or without Kian. I can't wait much longer.
** [ ] Take the Primary On-Call shift for the night
