This is a list of the current branches for the DoseSpot project, and how they relate to each other.

* V1 Branches
** [1/1] [#A] New env var DOSESPOT_DEFAULT_PROVIDER_ID
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3757][WE-468]]: Adds DOSESPOT_DEFAULT_PROVIDER_ID env var
** [2/2] AddPrescriptionsByCode
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3710][WE-409]]: CreateCodedFillRequestRx

- Note taken on [2024-02-04 Sun 11:20] \\
  I need to review this one, then it should be good to merge.
- Note taken on [2024-02-04 Sun 11:20] \\
  Qushawn is doing this one.
*** [X] WE-481: Replace "AddPrescriptionsByCode" functions with new service method
- Note taken on [2024-04-29 Mon 17:23] \\
  QA'd and ready to merge (Qushawn's ticket so he'll merge)
- Note taken on [2024-04-26 Fri 19:37] \\
  Need to make changes to this PR based on changes I made in WE-480
- Note taken on [2024-02-13 Tue 14:04] \\
  This requires a lot more work than I thought, because I have to make some changes to what exists. I don't think the service as currently implemented actually works.
** [2/2] AddPrescriptionsByFreeText
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3727][WE-410]]: CreateFreeTextFillRequest

- Note taken on [2024-02-04 Sun 11:24] \\
  Qushawn is doing this one.
- Note taken on [2024-02-04 Sun 11:24] \\
  I need to review this one.
- Note taken on [2024-02-04 Sun 11:22] \\
  Branched off of WE-409
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3954][WE-480]]: Replace "AddPrescriptionsByFreeText" functions with new service method
- Note taken on [2024-05-03 Fri 11:07] \\
  Error fixed, I mixed up the refills quantity with the dispense quantity
- Note taken on [2024-05-03 Fri 10:53] \\
  QA found an error with this one, where a 0 in the "refills" field will cause an error
:LOGBOOK:
CLOCK: [2024-05-03 Fri 10:53]--[2024-05-03 Fri 11:18] =>  0:25
:END:
- Note taken on [2024-05-02 Thu 18:09] \\
  In QA
- Note taken on [2024-04-29 Mon 17:23] \\
  In review
- Note taken on [2024-04-15 Mon 16:46] \\
  Waiting for WE-583 to be merged, then this one can be reviewed.
** [2/2] CancelPrescription
*** [X] WE-618: CancelPrescription service method
*** [X] WE-623: Replace "Cancel Prescription" functions with new service method
** [2/2] ChangePrescriptionPharmacy
- Note taken on [2024-02-05 Mon 10:41] \\
  Low priority, not found in our APM.
*** [X] WE-374: "ChangePrescriptionPharmacy" service method.
- Note taken on [2024-04-24 Wed 13:15] \\
  Ready to merge
- Note taken on [2024-04-16 Tue 13:14] \\
  Needs a few more tests before being marked as ready for review.
- Note taken on [2024-04-15 Mon 16:46] \\
  Waiting for WE-583 to be merged, then this one can be reviewed.
:LOGBOOK:
CLOCK: [2024-04-15 Mon 11:17]--[2024-04-15 Mon 11:42] =>  0:25
CLOCK: [2024-04-15 Mon 10:39]--[2024-04-15 Mon 11:04] =>  0:25
:END:
*** [X] WE-477: Replace "ChangePrescriptionPharmacy" functions with new service method.
- Note taken on [2024-04-15 Mon 17:23] \\
  This is blocked bo WE-380, since it relies on the Copy Prescription functionality.
- Note taken on [2024-04-15 Mon 16:47] \\
  Branched off of WE-374
** [2/2] Copy Prescription
- Note taken on [2024-02-05 Mon 10:42] \\
  Low priority, not found in our APM.
*** [X] WE-380: "CopyPrescription" service method.
*** [X] WE-478: Replace "CopyPrescription" functions with new service method.

** [2/2] DeletePendingRx
*** [X] WE-375: "DeletePendingRx" service method.
- Note taken on [2024-02-05 Mon 09:11] \\
  Qushawn is handling this one.
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3788][WE-479]]: Replace "DeletePendingRx" functions with new service method.
- Note taken on [2024-02-13 Tue 21:17] \\
  In review.
** [2/2] GetDispenseUnits
*** NO WE-628: GetDispenseUnits
- Note taken on [2024-05-06 Mon 09:20] \\
  DoseSpot is removing this endpoint in V2 (it's not in their docs) so we are not writing a service method for this.
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/4063][WE-630]]: Removes manage command to update DoseSpot dispesne units

** [1/1] GetMedicationByNameAndStrength
*** [X] WE-490: Replace "Get Medication by Name and Strength" functions with new service method.
** [1/1] GetMedicationByRxCUI
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3724/files][WE-460]]: Replace "Get Medications by RxCUI" functions with new service method

- Note taken on [2024-02-05 Mon 14:32] \\
  In review now.
- Note taken on [2024-02-04 Sun 16:37] \\
  This needs the PR that implements DOSESPOT_DEFAULT_PROVIDER_ID to work. Otherwise the tests are going to fail.
- Note taken on [2024-02-04 Sun 16:34] \\
  Testing: Go to a patient with a pending consultation request, fill that out, then submit the Rx. This method should get called.
- Note taken on [2024-02-04 Sun 16:34] \\
  Tested myself and it seems fine.
** [3/3] GetOrUpdatePatient
*** NO [[https://github.com/hellowisp/secure.hellowisp.com/pull/3633][WE-362]]: Add a CreateOrUpdatePatient service method for DoseSpot
- Note taken on [2024-02-04 Sun 10:19] \\
  This one is so old that it probably warrants a rewrite at this point. The merge on it will be awful, and I think it was written to replace the functionality as well. We should have a separate PR to implement the service, especially one this important.

*** [X] WE-488: Replace "CreateOrUpdatePatient" functions with new service method.
- Note taken on [2024-05-07 Tue 10:44] \\
  In test
- Note taken on [2024-04-30 Tue 17:34] \\
  Going to QA now. Passed code review.
- Note taken on [2024-02-08 Thu 18:03] \\
  We may want to do this one last. A lot of the undocumented places in Session that rely on add/edit patients will be removed when we finish other tasks.
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3978][WE-590]]: Refactor "CreateOrUpdatePatient"
** [3/3] GetPatientPrescriptions
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3732][WE-407]]: Implements the GetPatientPrescriptions service method.
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3754][WE-466]]: Implements the GetPatientPrescription service method.
- Note taken on [2024-02-04 Sun 10:11] \\
  Ready for review, but no reviews yet.

*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3755][WE-465]]: Utilizes both the above service methods in production.

- Note taken on [2024-02-13 Tue 14:14] \\
  In review
- Note taken on [2024-02-04 Sun 10:13] \\
  Verified myself that it works, but that's probably not good enough for a deploy this important.
- Note taken on [2024-02-04 Sun 10:12] \\
  In draft form, needs its base PRs merged before review. Could use some tests.

** [1/1] GetPharmacy
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3722][WE-458]]: Using new service for all DoseSpotPharmacy.get operations
- Note taken on [2024-02-04 Sun 10:21] \\
  The base is merged. May need tests for this.

** [2/2] SearchPharmacies
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3738][WE-413]]: Implements the SearchPharmacies service method.

- Note taken on [2024-02-04 Sun 10:09] \\
  Just waiting for CI to pass and then merge ASAP.

*** [X] WE-464: Utilize the SearchPharmacies service method.

- Note taken on [2024-02-06 Tue 12:58] \\
  May need to delete all the code surrounding this. Need to check if the manage command still works.
** [2/2] SendPrescriptions
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3749][WE-408]]: Implements a SendPrescriptions service method
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3756][WE-467]]: Using the new service method for all calls to `prescriptions/send`
- Note taken on [2024-02-14 Wed 17:08] \\
  Needs QA, but otherwise ready to deploy.
- Note taken on [2024-02-08 Thu 15:07] \\
  In review
- Note taken on [2024-02-04 Sun 10:25] \\
  Could probably use some tests. Existing tests may need to be updated.
- Note taken on [2024-02-04 Sun 10:25] \\
  Verified myself that it works.
- Note taken on [2024-02-04 Sun 10:24] \\
  In draft form. Needs the base merged before opening for review.
* V2 Branches
** [1/1] Authentication
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/4011][WE-360]]

- Note taken on [2024-04-23 Tue 17:38] \\
  Need tests, then this can go into review.
- Note taken on [2024-04-23 Tue 10:50] \\
  Back to work on this one.
- Note taken on [2024-02-08 Thu 17:48] \\
  I tried authenticating with the key they sent us, but I can't get it to work yet. Will come back to this once they answer my question about it.
- Note taken on [2024-02-04 Sun 18:57] \\
  We need to start on this ASAP, but it will require connecting to the V2 staging environment.
** [1/1] GetNofiticationsCounts
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3745][WE-426]]: Implements GetNotificationsCounts V2

** [1/1] Feature Flag for V2
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3746][WE-403]]: Implements a feature flag to toggle between DoseSpot's V1 and V2

- Note taken on [2024-02-09 Fri 10:53] \\
  Waiting to merge
- Note taken on [2024-02-08 Thu 14:42] \\
  In review
- Note taken on [2024-02-04 Sun 10:07] \\
  Waiting for WE-426 to be reviewed and merged, but this one should be ready for review as soon as the merge happens.

** [16/16] Branches
*** [X] [[https://hellowisp.atlassian.net/browse/WE-426][WE-426]]: Create "GetNofiticationsCounts" for DoseSpot V2
*** [X] WE-469: Create "AddPrescriptionsByCode" for DoseSpot V2
- Note taken on [2024-05-14 Tue 08:14] \\
  In review
- Note taken on [2024-05-10 Fri 12:15] \\
  Need to test this one myself, might be ready for review.
- Note taken on [2024-05-06 Mon 15:01] \\
  Cannot test the UI portion of this until WE-485 is complete
:LOGBOOK:
CLOCK: [2024-05-02 Thu 11:39]--[2024-05-02 Thu 12:04] =>  0:25
CLOCK: [2024-05-02 Thu 10:52]--[2024-05-02 Thu 11:17] =>  0:25
:END:
*** [X] WE-470: Create "AddPrescriptionsByFreeText" for DoseSpot V2
*** [X] WE-471: Create "ChangePrescriptionPharmacy" for DoseSpot V2
*** [X] WE-472: Create "CopyPrescription" for DoseSpot V2
*** [X] WE-473: Create "DeletePendingRx" for DoseSpot V2
- Note taken on [2024-04-29 Mon 17:22] \\
  Can't really proceed with this until we can add prescriptions to V2 (WE-469 or WE-470)
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3781][WE-474]]: Create "GetClinician" for DoseSpot V2
*** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3776][WE-475]]: Create "GetMedicationByNameAndStrength" for DoseSpot V2
- Note taken on [2024-02-14 Wed 08:22] \\
  Ready to merge
- Note taken on [2024-02-13 Tue 13:54] \\
  In review
*** [X] WE-476: Create "GetMedicationByRxCUI" for DoseSpot V2
- Note taken on [2024-05-13 Mon 09:31] \\
  Waiting to deploy
- Note taken on [2024-05-02 Thu 18:07] \\
  In review. We will figure out what to do about the data overwriting later. We need this to move forward with coded prescriptions.
- Note taken on [2024-05-02 Thu 12:01] \\
  As is, this will overwrite V1 data in the Product table with V2 data. Need to find a solution for this.
*** [X] WE-482: Create "GetPatientPrescription" for DoseSpot V2
- Note taken on [2024-05-14 Tue 08:12] \\
  Needs the DispenseUnitDescription fix. Will wait for Qushawn to finish his PR then branch off that.
- Note taken on [2024-05-08 Wed 09:25] \\
  Branched off WE-470. Will go into review once that branch is merged.
*** [X] WE-483: Create "GetPatientPrescriptions" for DoseSpot V2
- Note taken on [2024-05-08 Wed 09:26] \\
  Qushawn has this one.
*** [X] WE-484: Create "GetPharmacy" for DoseSpot V2
- Note taken on [2024-04-30 Tue 16:13] \\
  Can merge, will give everyone a bit longer to re-review.
- Note taken on [2024-04-29 Mon 17:21] \\
  In review
*** [X] WE-485: Create "SearchMedicationByName" for DoseSpot V2
- Note taken on [2024-05-08 Wed 09:26] \\
  Qushawn is on this one.
- Note taken on [2024-02-14 Wed 14:34] \\
  Probably going to leave this one as a draft, no way I'm going to finish this before Friday.
*** [X] WE-486: Create "SearchPharmacy" for DoseSpot V2
- Note taken on [2024-05-03 Fri 15:44] \\
  In review
:LOGBOOK:
CLOCK: [2024-05-03 Fri 14:16]--[2024-05-03 Fri 14:41] =>  0:25
CLOCK: [2024-05-03 Fri 12:15]--[2024-05-03 Fri 12:40] =>  0:25
CLOCK: [2024-05-03 Fri 11:27]--[2024-05-03 Fri 11:52] =>  0:25
CLOCK: [2024-05-03 Fri 10:03]--[2024-05-03 Fri 10:28] =>  0:25
:END:
*** [X] WE-487: Create "SendPrescriptions" for DoseSpot V2

- Note taken on [2024-05-13 Mon 09:32] \\
  Qushawn's got this one
*** [X] WE-489: Create "CreateOrUpdatePatient" for DoseSpot V2
* [15/15] Misc.
Other branches that are cleanup or not tied to a ticket

** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3715][refactor/remove-product-strength-search]]
** NO [[https://github.com/hellowisp/secure.hellowisp.com/pull/3619][refactor/remove-unused-dosespot-class]]
Done in another PR
** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3642][refactor/remove-provider-add]]
** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3725][refactor/remove-dosespot-get-pharmacy-command]]
** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3763][refactor/remove-search-medication-by-name-legacy]]
** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3777][fix/get-notifications-counts-v2]]
** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3778][refactor/remove-update-prescription-dosespot-rx]]
** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3789][feat/exception-for-unknown-dosespot-status-code]]
** [18/18] WE-576: Refactor the ERxService method interfaces to accept Provider IDs instead of Provider DoseSpot IDs
:LOGBOOK:
CLOCK: [2024-04-04 Thu 11:27]--[2024-04-04 Thu 11:52] =>  0:25
CLOCK: [2024-04-04 Thu 10:55]--[2024-04-04 Thu 11:20] =>  0:25
CLOCK: [2024-04-04 Thu 10:16]--[2024-04-04 Thu 10:41] =>  0:25
:END:
*** [X] ERxService.create_or_update_patient - CreateOrUpdatePatient
*** [X] ERxService.get_clinician_address - GetClinicianAddress
*** [X] ERxService.get_medication_by_name_and_strength - GetMedicationByNameAndStrength
*** [X] ERxService.get_medication_by_rxcui - GetMedicationByRxcui
*** [X] ERxService.get_notifications_counts - GetNotificationsCounts
*** [X] ERxService.get_patient_prescription - GetPatientPrescription
*** [X] ERxService.get_patient_prescriptions - GetPatientPrescriptions
*** [X] ERxService.get_pharmacy - GetPharmacy
*** [X] ERxService.search_medications_by_name - SearchMedicationsByName
*** [X] ERxService.search_pharmacies - SearchPharmacies
*** [X] ERxService.create_coded_fill_request_rx - CreateCodedFillRequestRx
*** [X] ERxService.create_free_text_fill_request_rx - CreateFreeTextFillRequestRx
*** [X] ERxService.send_prescriptions = SendPrescriptions
*** [X] ERxService.delete_pending_rx - DeletePendingRx
*** [X] IntegrationV2 - get_clinician (still passing dosespot ID straight down)
*** [X] Add an environment variable - ERX_DEFAULT_PROVIDER_ID
*** NO Maybe delete environment variable - DOSESPOT_DEFAULT_CLINICIAN_ID
- Note taken on [2024-04-04 Thu 11:43] \\
  Can be done once we get rid of the ~get_default_session()~ function, but that will come once the old ~Session~ class is gone.
*** [X] Get all the tests passing again
** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/3957][WE-583]]: Move ERx Service tests to the new test suite
- Note taken on [2024-04-15 Mon 08:05] \\
  In review
** [X] feat/base-dosespot-integration-methods
- Note taken on [2024-04-19 Fri 16:35] \\
  This will take the _get_pharmacy_dosespot_id and _get_prescription_dosespot_id_from_rx_id and move them to one PR.
** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/4012][refactor/dosespot_result_name]]
Changes ~DoseSpotAPIV1Result~ to ~DoseSpotAPIResult~ since V1 and V2 are the same.
Try merging as soon as possible.
** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/4019][refactor/remove-old-dosespot-api-result]]
Removes an unused class in the ~models/dosespot.py~ file.
Branched off of refactor/dosespot_result_name, merge as soon as possible.

** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/4003][feat/WE-360-notifications-rename]]
** [X] [[https://hellowisp.atlassian.net/browse/WE-624][feat/WE-624]]: Refactor Coded Prescriptions
:LOGBOOK:
CLOCK: [2024-05-02 Thu 09:05]--[2024-05-02 Thu 09:20] =>  0:15
CLOCK: [2024-05-02 Thu 08:35]--[2024-05-02 Thu 09:00] =>  0:25
:END:
** [X] [[https://github.com/hellowisp/secure.hellowisp.com/pull/4057][fix/get-clinician-v2]]: Fixes to get GetClinician V2 working
- Note taken on [2024-05-02 Thu 18:09] \\
  In review
** [4/4] Discovery: What fields changed between V1 and V2?
*** [X] Clinician
No changes
:LOGBOOK:
CLOCK: [2024-05-08 Wed 11:54]--[2024-05-08 Wed 11:57] =>  0:03
:END:
*** [X] Medication
Some changes.
**** All
- frontend/views/Provider/types/types.ts | TDosespotMedication
**** [X] CompoundIngredients (structure changed)
**** [X] LexiDrugSynId
**** [X] LexiGenDrugId
**** [X] LexiGenProductId
**** [X] LexiSynonymTypeId
**** [X] MonographPath
- Function: get_approval_email_text | line 876
- frontend/views/Provider/types/types.ts
- frontend/views/Provider/views/DoseSpot/views/ConsultationRequest/types.ts
**** [X] GenericProductName
- frontend/views/Provider/types/types.ts
- frontend/views/Provider/views/DoseSpot/views/ConsultationRequest/types.ts
- app/utils.py | Function: get_approval_email_text | line 854
*** [X] Pharmacy
Changes are fairly minimal. Only 1 field added and 2 removed.

Only fields removed are:
- IsDefault
- IsPreferred

I am fairly confident these are not used anywhere in the codebase.
*** [X] Prescription
Lots of changes. Things removed. It seems that a lot of the stuff available on Medications was removed. Maybe they expect us to query the Medications endpoint for the data we need.

We could take the DispensableDrugID and query for medications that way. Perhaps keep saving that data to the DB? Or query every time?

**** [3/5] All
***** [ ] frontend/views/Provider/views/DoseSpot/views/ConsultationRequest/types.ts | PendingDoseSpotRx
***** [ ] frontend/views/Provider/types/types.ts |
***** [X] app.controllers.erx_controller.ERxController._transform_ds_medication_to_erx_medication (not all, but the lexi ones)
***** [X] app.integrations.erx.dosespot.DoseSpotIntegration._transform_coded_erx_data_to_ds_dict (the lexi ones)
***** [X] app.models.catalog.product.Product.lexigen_ids (the lexi ones)

**** [X] DispenseUnitDescription
We can do John's idea for this one. Query the ~DispenseUnit~ table, and use the name for the ~DispenseUnitDescription~. No need to even hit the API again.
- app/views/old/layouts/read_component_object.html | line 899
- app/views/old/nurse/patient_prescriptions.html | line 23
- frontend/views/Provider/types/types.ts | line 274
- frontend/views/Provider/views/DoseSpot/views/ConsultationRequest/ConsultationRequest.PendingRxs.tsx | line 43
- frontend/views/Provider/views/DoseSpot/views/ConsultationRequest/ConsultationRequest.SentRxs.tsx | line 20
- frontend/views/Provider/views/DoseSpot/views/ConsultationRequest/types.ts | line 49
- frontend/views/Provider/views/DoseSpot/views/OrderHistory/OrderHistory.Prescriptions.tsx | line 12
***** [X] app/models/prescription.py | app.models.prescription.Prescription.build_dosespot_rx | line 166
Pulls from ~Product.units_dispensed~ so not a problem
**** [X] CompoundId
**** [X] DoseForm
***** HOLD app/utils.py | def render_rx_status | line 659,660
Probably a Prescription type, so maybe fine as is
**** [X] Route
***** HOLD app/utils.py | def render_rx_status | line 656,657
  Probably a Prescription type, so maybe fine as is
**** [X] Strength
***** HOLD app/utils.py | def render_rx_status | line 655
  Probably a Prescription type, so maybe fine as is
  It's under an ~if~ statement, so theoretically, things should still work. It's just that on that page, "Strength" will never show.
***** [X] app.models.catalog.product.Product.strength | line 252
This one is fine. It's on the Product (Medication) so no problem.
**** [X] GenericProductName

- app/utils.py | line 854
**** [X] GenericDrugName
**** [X] LexiGenProductId
**** [X] LexiDrugSynId
**** [X] LexiSynonymTypeId
**** [X] LexiGenDrugId
**** [X] RxCUI
- NOTE: There is the "rxcui" column on the Product model. Worth investigating.
  - If anything, I think this means we don't have to worry about this one much. Why would they use the DoseSpot Medatada RxCUI when the DB one is available?
***** [ ] app/utils.py | line 883 (not sure if this is a prescription or medication)
***** [ ] frontend/views/Provider/views/DoseSpot/hooks/useMedMetadata.ts | setFieldValue('product_rxcui', data.RxCUI) | line 24
***** [ ] frontend/views/Provider/views/DoseSpot/views/MedSelection/MedSelection.tsx | setFieldValue('product_rxcui', data.RxCUI) | line 44

**** [X] OTC
**** [?] NDC
- frontend/views/Provider/types/rxTypes.ts | line 22
- NOTE: There is the "ndc" column on the Product model. Worth investigating.
**** [X] Schedule
- app/controllers/rx_preapproval_request_controller.py | app.controllers.rx_preapproval_request_controller.RxPreapprovalRequestController._process_prescription | line 83
- app/models/catalog/product.py | app.models.catalog.product.Product.drug_schedule | line 264
**** [X] MonographPath
- See above under Medication. I don't know which instances belong to which.
**** [X] DrugClassification
**** [X] Brand

**** Data points in Medication:
***** NDC
***** DoseForm
***** Route
***** Strength
***** GenericDrugName
***** Schedule
***** RxCUI
***** OTC
***** DrugClassification (data may have changed from Lexi to MediSpan)
***** Brand
**** Data points not in Medication:
***** LexiGenProductId
***** LexiDrugSynId
***** LexiSynonymTypeId
***** LexiGenDrugId
***** CompoundId
***** DispenseUnitDescription (maybe can get this from DispenseUnitId with lookup)
***** GenericProductName
***** MonographPath (need to verify if we have access to this endpoint)
* Other
Clinic Key for Test Clinic 1 in staging

LYV6WVAXJ2YTDYTYRHQ3NKMQ7Q3VRP3M


https://my.staging.dosespot.com/webapi/v2/connect/token

x-www-form-urlencoded

POST https://my.staging.dosespot.com/webapi/v2/connect/token
Content-Type: application/x-www-form-urlencoded
Subscription-Key: {subscription_key}
Content-Length: 327

client_id={client_id}&client_secret={client_secret}&username={username}&password={password}&scope=api&grant_type=password


Primary:
f234dac2e5356887df8c2a70f712ca9d5b6c962d9b833239082b9d0b14b43e4f

Secondary:
96fb53492e97b9f0f1f17ff510724a32134d79069a3636f5e9e7f4644aaee3b1


Arnold Bays DoseSpot ID V1: 226139
Arnold Bays DoseSpot ID V2: 300787

** [ ] Investigate if "Search Medication by Name and Strength" V2 even works. Pretty sure it doesn't.


* Things to do before V2 switch
** NO Switch ~dosespot_id~ in all rows in Provider table to their new DoseSpot V2 IDs. Or add a V2 column if we want to keep the original IDs.
We don't need to do this.
** [?] Plan the transition from Prescription V1 IDs and data to V2
- Note taken on [2024-05-14 Tue 08:17] \\
  We cannot proceed until DoseSpot gives us the Excel sheet.
** [X] Ask DoseSpot if the Provider DoseSpot IDs will change in production as part of V2 transition.
They confirmed that they Provider DoseSpot IDs will not change.

* Questions for DoseSpot
** [X] Will Pharmacy IDs stay the same between V1 and V2?
- Note taken on [2024-05-06 Mon 13:12] \\
  The answer is "Yes"
Need to know because we store the Pharmacies locally. If they are not the same, we may need a new table.
** [X] Ask if the 'GetDispenseUnit' endpoint has been removed
- Note taken on [2024-05-06 Mon 13:11] \\
  Confirmed it is removed for V2
- Note taken on [2024-05-06 Mon 08:53] \\
  They once again failed to answer the question
- Note taken on [2024-05-03 Fri 17:44] \\
  Asked on their support site
* Models we save for DoseSpot
** DoseSpotPharmacy
*** data
Stores a JSON dump of DoseSpot's data. There are some minor differences in V2, but we probably want to overwrite our old data here.
** Patient
*** dosespot_id
The patient's DoseSpot ID. Shouldn't change, but we'll ask.
** Pharmacy
The entire table saves DoseSpot's pharmacy data into columns. We don't save everything. Probably fine as is.
** Product
*** dosespot_drug_metadata
Stores a JSON dump of DoseSpot's data. This data will be different in V2.
** Providers
*** dosespot_id
We need to ask DoseSpot if this will be the same between V1 and V2. No reason it shouldn't be (but this is DoseSpot we're talking about, so who knows).
** Rx
*** dosespot_rx
Stores a JSON dump of DoseSpot's prescription data. This will be different for V2, since this stores LexiGen data.

* Things to tell the group
** [X] DoseSpot is going to give us an Excel sheet in the next week or two (as of May 6th) which will show which Lexi IDs correspond to which MediSpan IDs.
This should give us some options when migrating our data from V1 to V2.

** [X] MonographPath may be a bit tricky. They supplied us with a URL that we have been using to direct patients, but that has been replaced by an API endpoint.
The URL looked like this:
"https://{dosespot_domain}/secure/Monographs/{url_fragment}"
~url_fragment~ looks like this: ~HTMLICONS/d00112a1.htm~
** [X] We don't save allergy info in DoseSpot. There is an API endpoint for this, so we could.
